### ISSUE TITLE
有 api 了

### ISSUE THREAD

**Issue by sleepm** [ShuYingJiYu/COVID-19-risk-area#3]
http://bmfw.www.gov.cn/bjww/interface/interfaceJson
json挺清晰的
界面交互不好的锅后端不背……

**Comment by SakuraPuare** [comment]
有加密 有签名，求怎么请求

**Comment by SakuraPuare** [comment]
![image](https://user-images.githubusercontent.com/52142762/189483740-c293717a-415e-4b2b-bc98-7034310c7a8d.png)
![image](https://user-images.githubusercontent.com/52142762/189483752-5a8505ac-fbd4-4680-a27f-42182ba3e1fa.png)
在开发初期我也找到了此接口，但找到了接口没用，还要学会如何请求。

**Comment by sleepm** [comment]
https://blog.csdn.net/kylner/article/details/125309260
我翻了下 http://bmfw.www.gov.cn/yqfxdjcx/source/PC/js/risk.25cebd5f.js
有个地方没搞明白，23y0ufFl5YxIyGrI8hWRUZmKkvtSjLQA
然后搜出来的csdn……

**Comment by SakuraPuare** [comment]
收到，说实话，做这个工具有一定的任务（
所以没有仔细研究JavaScript，直接用了selenium
正在修改后端查询相关代码

**Comment by SakuraPuare** [comment]
已更新 [✨ feat: API获取数据](https://github.com/ShuYingJiYu/COVID-19_Risk_Area_Backend/commit/a887008219cff7715fad995109ec2dd6cd726658)
